Des 61 filter by pending
LBHackney-IT/evidence-api pull request #25
Opened 2021-02-02 12:25 UTC by bogdan-zaharia

## Link to JIRA ticket

https://hackney.atlassian.net/jira/software/projects/DES/boards/45?selectedIssue=DES-61

### *What changes have we introduced*

Added request object for getting evidence requests and refactored gateway function to accept this argument
Added evidence request function to determine the state based on document submissions state

#### _Checklist_

- [ ] Added end-to-end (i.e. integration) tests where necessary e.g to test complete functionality of a newly added feature
- [ ] Added tests to cover all new production code
- [ ] Added comments to the README or updated relevant documentation _(add link to documentation)_, where necessary.
- [ ] Checked all code for possible refactoring
- [ ] Code pipeline builds correctly

### *Follow up actions after merging PR*

Are there any next steps that need to addressed after merging this PR? Add them here.

2021-02-05 12:24 UTC, samtgarson requested changes
Good stuff overall, a couple of comments, but one major one:

I believe the logic in the `UpdateEvidenceRequestState` use case is incorrect, and it's untested.

I'd recommend going back now and starting by writing test cases for the different cases (`Approved`, `ForReview`, `Pending`), and then use them to build the correct logic in the use case

2021-02-05 12:24 UTC, samtgarson commented on EvidenceApi.Tests/V1/Domain/EvidenceRequestTests.cs
> +            documentTypes.Add("passport");
```suggestion
            var documentTypes = new List<string>() { "passport" }
```

2021-02-05 12:24 UTC, samtgarson commented on EvidenceApi.Tests/V1/Domain/EvidenceRequestTests.cs
> +            communications.Add(TestDataHelper.Communication());
Same here ☝️

2021-02-05 12:24 UTC, samtgarson commented on EvidenceApi.Tests/V1/Domain/EvidenceRequestTests.cs
> +            documentSubmissions.Add(TestDataHelper.DocumentSubmission());
Same here ☝️

2021-02-05 12:24 UTC, samtgarson commented on EvidenceApi.Tests/V1/Domain/EvidenceRequestTests.cs
> +            deliveryMethods.Add("Sms");
same here ☝️

2021-02-05 12:24 UTC, samtgarson commented on EvidenceApi.Tests/V1/Gateways/EvidenceGatewayTests.cs
> +        public List<EvidenceRequest> ExpectedEvidenceRequests(Resident? resident = null, EvidenceRequestState? state = null)
Not quite sure I understand what this method is doing? It adds all the same attributes to both evidence requests, so how is it testing the filtering functionality

2021-02-05 12:24 UTC, samtgarson commented on EvidenceApi/V1/Domain/EvidenceRequest.cs
> +        // }
👀

2021-02-05 12:24 UTC, samtgarson commented on EvidenceApi/V1/Gateways/EvidenceGateway.cs
> +                ).ToList();
This is nice now 👏

2021-02-05 12:24 UTC, samtgarson commented on EvidenceApi/V1/UseCase/UpdateEvidenceRequestStateUseCase.cs
> +            else
don't need an `else` if there's a `return` above

2021-02-05 12:24 UTC, samtgarson commented on EvidenceApi/V1/UseCase/UpdateEvidenceRequestStateUseCase.cs
> +        public EvidenceRequestState Execute(Guid id)
This function could do with a refactor/optimisation, but for now its good 👍

2021-02-10 15:19 UTC, neilmendum commented on EvidenceApi/V1/UseCase/UpdateEvidenceRequestStateUseCase.cs
> +            if (evidenceRequest.DocumentTypes.ToArray().All(dt =>
One way of making this, and the other statement below checking if any evidence requests are in _Uploaded_ state, a bit more readable is to extract the logic into 2 private methods. It's good practice to name them something descriptive, for example `allEvidenceRequestsAreApproved`. See [here](https://refactoring.guru/decompose-conditional) for more info

2021-02-10 15:19 UTC, neilmendum commented on EvidenceApi/V1/UseCase/UpdateDocumentSubmissionStateUseCase.cs
> +            if (String.IsNullOrEmpty(request.State))
Would be good to write a test case for this, unless I missed it

2021-02-11 10:37 UTC, neilmendum approved these changes

2021-02-11 10:59 UTC, samtgarson approved these changes

2021-02-11 15:51 UTC, merged